### PR TITLE
GH-23: Fix unlock date format and location

### LINKED ISSUE #23: Unlock date displays in the incorrect format and location
image

Need to:

- Fix date/time format (not 1970)
- Display the date in the top right (I figure some element needs a flex-grow maybe)

### PR DESCRIPTION
**Pull request by lcombs15**
image

closes #23

### CODE REVIEW

File: src/components/achievement-card/achievement-card.tsx [hunk 1]
```diff
@@ -7,32 +7,36 @@ interface AchievementCardProps {
...
     return (
         <div className={"border-4 flex rounded-md border-blue-400 p-1 " + backgroundColor}>
             <img className={"w-12 h-12"}
-                 src={props.achievement.unlocked ? props.achievement.icon : props.achievement.iconGray}
+                 src={unlocked ? icon : iconGray}
                  alt={"achievement icon"}/>
-            <div className={"flex-col pb-2 pl-1"}>
-                <h3 className="font-bold">{props.achievement.name}</h3>
-                <p className="text-xs">{props.achievement.description}</p>
+            <div className={"flex-col pb-2 pl-1 grow"}>
```
Comment (lcombs15) [inline src/components/achievement-card/achievement-card.tsx:33]: This line is the format magic, asks this center div to take up the extra space and pushes the date to the right

**Review by tiemonl — APPROVED** [review]
